### ISSUE TITLE
Usecase of this repo 

### ISSUE THREAD

**Issue by yashcrest** [JonmarCorpuz/SecondBrain#1]
Hi Jonmar, 

I saw your profile on LinkedIn and was impressed by your home lab setup that closely reflected the one of Enterprise Network setup. I am trying to understand the use case of this repository, as the repo seem to be containing only markdown files with basic information.

**Comment by jonmarcorpuz** [comment]
Hey Yash,

This repo is simply a second brain, which is a system of organizing and managing information. This second brain allows me to dump and store the information and knowledge that I gain throughout everything I do and serves as a reference point for whenever I need to refresh myself on a certain topic.

I hope this comment helped you understand more the use case of this repo!

**Comment by yashcrest** [comment]
Thank you for replying Jonmar. This looks very good way to organize your notes and to refer to it at later stage. 

I have been personally using Notion for note taking and organising, should give method a try too. :)

**Comment by jonmarcorpuz** [comment]
It's my pleasure Yash and thank you! I used to use Obsidian to publish my notes but I also wanted my notes to be freely accessible to anyone over the Internet and I had to pay a subscription fee to do so, so I just decided to publish my notes on Github since I've already been using it to share my other projects and people can access my page without me having to pay anything for them to do so. 

I also personally use Notion and it's really great! But I mostly use it for keeping a list of general topics that I want to touch on and organizing my ideas for various projects I have in mind.

**Comment by yashcrest** [comment]
Hey Jomar, 

Sorry for circling back after so long, as I just now understand the concept of Obsidian notes and Zettelkasten noting taking method. 

I just wanted to ask if you were using github as a way to sync your notes and use it as the vault for your obsidian setup?

**Comment by jonmarcorpuz** [comment]
Hello @yashcrest ! No worries, thank you for reaching back. I don't have my Github synced with anything. I'm simply using Github as a replacement for Obsidian since I'm able to publicly share my notes here for free. I hope this answers your question. If not, please let me know!
